[env:MKS_TFT28_V4_0]
platform             = ststm32
framework            = cmsis
board                = STM32F107VC_0x7000
board_build.filename = MKSTFT28
lib_ldf_mode         = off

build_flags =
  -DUSE_STDPERIPH_DRIVER
  -DSTM32F10X_CL
  -DHSE_VALUE=25000000ul
  -DVECT_TAB_FLASH=0x08007000
  -DRAM_SIZE=64
  -DMKS_TFT28_V4_0
  -DMKS_TFT
  -DSYSTEM_LANGUAGE=ENGLISH
  -fmax-errors=5 -g -ggdb -Wno-missing-braces
  -Wl,--allow-multiple-definition

extra_scripts =
  pre:scripts/auto_includes.py
  scripts/stm32f107xC_0x7000_iap.py
  post:scripts/deploy_assets.py
