[env:MKS_TFT28_V4_0]
platform        = ststm32
framework       = cmsis
board           = STM32F107VC_0x7000
# deep+ est indispensable ici pour traverser l'arborescence complexe
lib_ldf_mode    = off

build_flags = 
  -DUSE_STDPERIPH_DRIVER
  -fmax-errors=5 -g -ggdb -Wno-missing-braces
  -Wl,--allow-multiple-definition
  -DSOFTWARE_VERSION=\"28.x\"
  -DSOFTWARE_VERSION_SHORT=\"28\"
  -DSTM32F10X_CL
  -DHSE_VALUE=25000000ul
  -DVECT_TAB_FLASH=0x08007000
  -DRAM_SIZE=64
  -DMKS_TFT28_V4_0
  -DMKS_TFT
  # Dossier racine et configuration globale
  -Isrc
  -Ilib
  -Ilib/Variants
  -Ilib/Variants/Resolution
  # API & Graphisme
  -Ilib/API
  -Ilib/API/Language
  -Ilib/API/UI
  # Hardware & Drivers écran
  -Ilib/Hal
  -Ilib/Hal/stm32f10x
  -Ilib/Hal/LCD_Driver
  # Pile USB complète (Core, Classes, Driver OTG et Mode Utilisateur)
  -Ilib/Hal/STM32_USB_HOST_Library/Core/inc
  -Ilib/Hal/STM32_USB_HOST_Library/Class/MSC/inc
  -Ilib/Hal/STM32_USB_HOST_Library/Usr/inc
  -Ilib/Hal/STM32_USB_OTG_Driver/inc
  # Framework CMSIS & Standard Peripherals
  -Ilib/cmsis/stm32f10x
  -Ilib/fwlib/stm32f10x
  -Ilib/fwlib/stm32f10x/inc
  # 🟢 Le système de fichiers manquant :
  -Ilib/Fatfs

extra_scripts =
  pre:scripts/auto_includes.py
  scripts/stm32f107xC_0x7000_iap.py
  post:scripts/deploy_assets.py